### ISSUE TITLE
Consider removing the kafka_server prefix added to all Yammer metrics

### ISSUE THREAD

**Issue by mimaison** [strimzi/metrics-reporter#50]
We currently inject the `kafka_server_` prefix to all Yammer metrics. https://github.com/strimzi/metrics-reporter/blob/main/src/main/java/io/strimzi/kafka/metrics/yammer/YammerMetricWrapper.java#L44

The original idea was to made all broker-side metrics start with the same prefix to get a similar behavior than client-side metrics (all producer metrics start with `kafka_producer_`, same for the consumer, Streams and Connect).

However this creates some issues:
- The Kafka metrics from the broker already start with `kafka_server_`, so these currently become `kafka_server_kafka_server_<METRIC>`, for example: `kafka_server_kafka_server_replicamanager_leadercount`. 
- The Yammer metrics retrieved through JMX did not have the `kafka_server_` prefix. For example we had `kafka_controller_controllerstats_uncleanleaderelections_total `. Currently the reporter creates `kafka_server_kafka_controller_controllerstats_uncleanleaderelectionspersec_total` for that metric. Dropping the prefix could ease the transition.

For these 2 reasons, I propose removing the `kafka_server_` prefix we add to Yammer metrics.

Here is a gist comparing both the current output and the output if the remove the prefix: https://gist.github.com/mimaison/6731c7f088080e4d766c87f3280e2814

**Comment by mimaison** [comment]
@k-wall @OwenCorrigan76 thoughts?

**Comment by OwenCorrigan76** [comment]
@mimaison Yes that is much cleaner. I hadn't noticed `kafka_server_kafka_server_<METRIC>`.

It makes sense to deop the prefix, especially if the previous way (using JMX) did not have the `kafka_server_` prefix.

**Comment by k-wall** [comment]
+1
