### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by erikgb** [strimzi/metrics-reporter#52]
To make it easier to try/use this component, releases should be published to public artifact repositories as Maven Central.

**Comment by scholzj** [comment]
It will be published to Maven Central when it has some release. But right now there is no release and nothing to publish.

**Comment by erikgb** [comment]
> It will be published to Maven Central when it has some release. But right now there is no release and nothing to publish.

Makes sense. Is there anything blocking publishing a pre-release?

**Comment by scholzj** [comment]
Pre-releases are not supposed to be published to Maven Central and we do not publish them there. They are in a staging repository that you can use for testing - it is listed in the Git HUb Release.

**Comment by scholzj** [comment]
FYI: 0.1.0 is now released and is in Maven Central.

**Comment by erikgb** [comment]
Thanks! Both for the release and the notification! ❤️
